classdef PointCloudData
    %POINTCLOUDDATA Model object for one period of XYZ point-cloud data.

    properties
        points
        name
        period
        sourcePath
        bounds
        zStats
        qualityReport
        cleaned
        history
    end

    methods
        function obj = PointCloudData(points, name, period, sourcePath)
            if nargin < 1 || isempty(points)
                points = zeros(0, 3);
            end
            if nargin < 2
                name = "";
            end
            if nargin < 3
                period = "";
            end
            if nargin < 4
                sourcePath = "";
            end

            validateattributes(points, {'numeric'}, {'2d', 'ncols', 3}, mfilename, 'points');
            obj.points = double(points);
            obj.name = char(name);
            obj.period = char(period);
            obj.sourcePath = char(sourcePath);
            obj.cleaned = false;
            obj.history = {};
            obj = obj.refreshStats();
        end

        function obj = refreshStats(obj)
            pts = obj.points;
            n = size(pts, 1);
            if n == 0
                obj.bounds = geodem.model.PointCloudData.emptyBounds();
                obj.zStats = geodem.model.PointCloudData.emptyStats();
                obj.qualityReport = geodem.model.PointCloudData.emptyQuality();
                return;
            end

            x = pts(:, 1);
            y = pts(:, 2);
            z = pts(:, 3);
            obj.bounds = struct( ...
                'XMin', min(x), 'XMax', max(x), ...
                'YMin', min(y), 'YMax', max(y), ...
                'ZMin', min(z), 'ZMax', max(z), ...
                'Width', max(x) - min(x), ...
                'Height', max(y) - min(y), ...
                'Area', max((max(x) - min(x)) * (max(y) - min(y)), 0), ...
                'PointCount', n);
            obj.zStats = struct( ...
                'Min', min(z), ...
                'Max', max(z), ...
                'Mean', mean(z, 'omitnan'), ...
                'Median', median(z, 'omitnan'), ...
                'Std', std(z, 'omitnan'), ...
                'P01', prctile(z, 1), ...
                'P99', prctile(z, 99));
            density = NaN;
            if obj.bounds.Area > 0
                density = n / obj.bounds.Area;
            end
            sigma = obj.zStats.Std;
            if sigma > 0
                outlierMask = abs(z - obj.zStats.Mean) > 3 * sigma;
            else
                outlierMask = false(size(z));
            end
            obj.qualityReport = struct( ...
                'PointCount', n, ...
                'FinitePointCount', sum(all(isfinite(pts), 2)), ...
                'InvalidPointCount', sum(~all(isfinite(pts), 2)), ...
                'Density', density, ...
                'Outlier3SigmaCount', sum(outlierMask), ...
                'Outlier3SigmaRatio', sum(outlierMask) / max(n, 1), ...
                'Bounds', obj.bounds, ...
                'ZStats', obj.zStats);
        end

        function summary = summaryTable(obj)
            summary = table( ...
                string(obj.name), string(obj.period), obj.bounds.PointCount, ...
                obj.bounds.XMin, obj.bounds.XMax, obj.bounds.YMin, obj.bounds.YMax, ...
                obj.bounds.ZMin, obj.bounds.ZMax, obj.zStats.Mean, obj.zStats.Std, ...
                obj.qualityReport.Density, ...
                'VariableNames', {'Name','Period','PointCount','XMin','XMax','YMin','YMax','ZMin','ZMax','ZMean','ZStd','Density'});
        end
    end

    methods (Static)
        function bounds = emptyBounds()
            bounds = struct( ...
                'XMin', NaN, 'XMax', NaN, ...
                'YMin', NaN, 'YMax', NaN, ...
                'ZMin', NaN, 'ZMax', NaN, ...
                'Width', 0, 'Height', 0, 'Area', 0, 'PointCount', 0);
        end

        function stats = emptyStats()
            stats = struct('Min', NaN, 'Max', NaN, 'Mean', NaN, 'Median', NaN, 'Std', NaN, 'P01', NaN, 'P99', NaN);
        end

        function report = emptyQuality()
            report = struct( ...
                'PointCount', 0, ...
                'FinitePointCount', 0, ...
                'InvalidPointCount', 0, ...
                'Density', NaN, ...
                'Outlier3SigmaCount', 0, ...
                'Outlier3SigmaRatio', 0, ...
                'Bounds', geodem.model.PointCloudData.emptyBounds(), ...
                'ZStats', geodem.model.PointCloudData.emptyStats());
        end
    end
end
